# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/mt6895-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter aristotle plato rubens xaga,$(TARGET_DEVICE)),)

endif
